# Generated by Django 6.1.1 on 2026-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='+56 9 ', max_length=20),
        ),
    ]
