# Generated by Django 6.1 on 2026-08-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
    ]
